### ISSUE TITLE
spring boot 项目中引用报错

### ISSUE THREAD

**Issue by havies** [xiaoyao9184/hj-t212-parser#13]
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonStreamContext.<init>(II)V
	at com.fasterxml.jackson.databind.util.TokenBufferReadContext.<init>(TokenBufferReadContext.java:59)
	at com.fasterxml.jackson.databind.util.TokenBufferReadContext.createRootContext(TokenBufferReadContext.java:89)
	at com.fasterxml.jackson.databind.util.TokenBuffer$Parser.<init>(TokenBuffer.java:1298)
	at com.fasterxml.jackson.databind.util.TokenBuffer.asParser(TokenBuffer.java:276)
	at com.fasterxml.jackson.databind.util.TokenBuffer.asParser(TokenBuffer.java:242)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3719)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3656)
	at com.xy.format.hbt212.core.converter.DataConverter.lambda$9(DataConverter.java:106)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.xy.format.hbt212.core.converter.DataConverter.convertPollution(DataConverter.java:109)
	at com.xy.format.hbt212.core.converter.DataConverter.convertDataLevel(DataConverter.java:159)
	at com.xy.format.hbt212.core.converter.DataConverter.convertDataLevel(DataConverter.java:201)
	at com.xy.format.hbt212.core.converter.DataConverter.convert(DataConverter.java:212)
	at com.xy.format.hbt212.core.deser.DataDeserializer.deserialize(DataDeserializer.java:97)
	at com.xy.format.hbt212.core.deser.DataDeserializer.deserialize(DataDeserializer.java:91)
	at com.xy.format.hbt212.core.deser.DataDeserializer.deserialize(DataDeserializer.java:77)
	at com.xy.format.hbt212.core.deser.DataDeserializer.deserialize(DataDeserializer.java:1)
	at com.xy.format.hbt212.core.T212Mapper._readValueAndClose(T212Mapper.java:177)
	at com.xy.format.hbt212.core.T212Mapper.readValue(T212Mapper.java:171)
	at com.xy.format.hbt212.core.T212Mapper.readData(T212Mapper.java:408)
	at com.open.HJ212Tests.readData(HJ212Tests.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by xiaoyao9184** [comment]
@havies  我认为这是Jackson版本的问题，请排查是否为2.9.3版本或更高

**Comment by havies** [comment]
目前把源码编译成 jar包后再引用到maven 项目中可以正常使用了，感谢回复

**Comment by xiaoyao9184** [comment]
@havies 本项目已经托管在 jitpack， 无需自行编译jar包，使用方式请看 https://jitpack.io/#xiaoyao9184/hj-t212-parser
